In [14]:
import numpy as np
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3],[4,5,6,7]])

multi = np.dot(A,B)

print(multi)
multi.max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


np.int64(47)